format = """
$hostname\
[░▒▓](#a3aed2)\
[  ](bg:#a2aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$python\
[](fg:#212736 bg:#1d2230)\
[](fg:#1d2230)\
\n$character"""

command_timeout = 1000


[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"

[hostname]
format = "[$ssh_symbol]($style)[$hostname](fg:#769ff0 bg:#394260) "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[( $all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[python]
style = "bg:#212736"
format = '[[( $virtualenv )](fg:#4B8BBE bg:#212736)]($style)'
